CREATE TABLE IF NOT EXISTS public.review (
    review_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_text TEXT NOT NULL,
    review_rating INT NOT NULL CHECK (review_rating >= 1 and review_rating <= 5),
    review_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    account_id INT NOT NULL REFERENCES public.account(account_id) ON DELETE CASCADE,
    inv_id INT NOT NULL REFERENCES public.inventory(inv_id) ON DELETE CASCADE
)